version: '2'
services:
  consul:
    build: consul/
    image: jonbrouse/consul
    container_name: consul
    hostname: consul
    command: agent -server -bootstrap-expect 1 -ui-dir /consul/ui -config-dir /consul/conf.d
    volumes:
      - ./consul/assets/conf.d:/consul/conf.d
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  vault:
    build: vault/
    image: jonbrouse/vault
    container_name: vault
    hostname: vault
    command: server -config=/vault/conf.d/vault.hcl
    volumes:
      - ./vault/assets/conf.d:/vault/conf.d
    ports: 
      - "8200:8200"
    links:
      - consul
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
  flask:
    build: flask/
    image: jonbrouse/flask
    container_name: flask
    hostname: flask
    command: --app=sample_app dev --hostname=0.0.0.0
    volumes:
      - ./flask/assets/sample_app/__init__.py:/opt/sample_app/__init__.py
    ports: 
      - "5000:5000"
#    links:
#      - consul
